name: Windows test

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - run: |
        python -c "import sys; print(sys.stdout.encoding, type(sys.stdout.buffer.raw))"
      shell: pwsh

    - run: |
        python -c "import sys; print(sys.stdout.encoding, type(sys.stdout.buffer.raw))"
      shell: bash

    - run: |
        chcp 932
        python -c "import sys; print(sys.stdout.encoding, type(sys.stdout.buffer.raw))"
      shell: cmd

    - run: |
        import sys
        import subprocess
        p = subprocess.run(
            [sys.executable, '-c', 'import sys; print(sys.stdout.encoding, type(sys.stdout.buffer.raw), file=sys.stderr)'],
            creationflags=subprocess.CREATE_NEW_CONSOLE,
            check=True,
            stderr=subprocess.PIPE,
        )
        print(p.stderr)
      shell: python
