name: Windows test

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: is a tty?
      run: |
        python -c "import os, sys; print(os.isatty(sys.stdout.fileno()))"

    - run: |
        python -c "import sys; print(sys.stdout.encoding, type(sys.stdout.buffer.raw))"
      shell: pwsh

    - run: |
        python -c "import sys; print(sys.stdout.encoding, type(sys.stdout.buffer.raw))"
      shell: bash

    - run: |
        chcp 932
        python -c "import sys; print(sys.stdout.encoding, type(sys.stdout.buffer.raw))"
      shell: cmd

    - run: |
        import sys
        import subprocess
        code = """\
        import sys
        with open("hoge.txt", "w", encoding="utf-8") as f:
            print(sys.stdout.encoding, type(sys.stdout.buffer.raw).__name__, file=f)
            print(f.encoding, type(f.buffer.raw).__name__, file=f)
        """
        p = subprocess.run(
            [sys.executable, '-c', code],
            creationflags=subprocess.CREATE_NEW_CONSOLE,
            check=True,
        )
        with open("hoge.txt", "r", encoding="utf-8") as f:
            print(f.read())
      shell: python
